# screen width and height
WIDTH, HEIGHT = 1280, 720
CENTER_SCREEN = WIDTH // 2
# Entity types
SPRITE_TYPE_PLAYER = 1 << 0
SPRITE_TYPE_BULLET = 1 << 1
SPRITE_TYPE_ASTEROID = 1 << 2
# Game States
STATE_MENU = 1 << 0
STATE_PLAY = 1 << 1
STATE_CONTROLS = 1 << 2
STATE_DEATH = 1 << 3
# buttons
MOUSE_BTN_1 = 0
BTN_ROUNDED = 10
BTN_WIDTH = 200
BTN_HEIGHT = 50
BTN_PAD = 10
# animation scaler
SPRITE_SCALER = 3
SPRITE_COLOR_KEY = (255, 255, 255)
